### ISSUE TITLE
Libc not in glibc-all-in-one can not be patched to a version nearby

### ISSUE THREAD

**Issue by YOURLEGEND** [ef4tless/xclibc#1]
## 情况简介

pwn题目录下如下
```
$ ls
exp_heap1.py  hacknote  libc_32.so.6
```

libc版本2.23，32位
```
$ file libc_32.so.6 
libc_32.so.6: ELF 32-bit LSB shared object, Intel 80386, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux.so.2, BuildID[sha1]=d26149b8dc15c0c3ea8a5316583757f69b39e037, for GNU/Linux 2.6.32, stripped
$ ./libc_32.so.6 
GNU C Library (Ubuntu GLIBC 2.23-0ubuntu5) stable release version 2.23, by Roland McGrath et al.
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 5.4.0 20160609.
Available extensions:
	crypt add-on version 2.1 by Michael Glad and others
	GNU Libidn by Simon Josefsson
	Native POSIX Threads Library by Ulrich Drepper et al
	BIND-8.2.3-T5B
libc ABIs: UNIQUE IFUNC
For bug reporting instructions, please see:
<https://bugs.launchpad.net/ubuntu/+source/glibc/+bugs>.
```

## 问题

如下执行命令尝试更换程序libc，失败
```
$ xclibc -x hacknote  libc_32.so.6 
Getting 2.23-0ubuntu5_i386
  -> Location: https://mirror.tuna.tsinghua.edu.cn/ubuntu/pool/main/g/glibc/libc6_2.23-0ubuntu5_i386.deb
  -> Downloading libc binary package
Getting 2.23-0ubuntu5_i386
  -> Location: http://old-releases.ubuntu.com/ubuntu/pool/main/g/glibc/libc6_2.23-0ubuntu5_i386.deb
  -> Downloading libc binary package
Failed to download package from http://old-releases.ubuntu.com/ubuntu/pool/main/g/glibc/libc6_2.23-0ubuntu5_i386.deb
```

并没有`libc6_2.23-0ubuntu5_i386.deb`这个包，而是 [libc6_2.23-0ubuntu11.3_amd64.deb](https://mirror.tuna.tsinghua.edu.cn/ubuntu/pool/main/g/glibc/libc6_2.23-0ubuntu11.3_amd64.deb) 或者[libc6_2.23-0ubuntu3_amd64.deb](https://mirror.tuna.tsinghua.edu.cn/ubuntu/pool/main/g/glibc/libc6_2.23-0ubuntu3_amd64.deb)

## 建议解决方案

建议增加临近版本匹配功能

**Comment by ef4tless** [comment]
非常感谢你的issue！
对于你建议的临近版本匹配，你是希望当选择libc_32.so.6 时，自动加载libc6_2.23-0ubuntu3_amd64.deb版本。还是当你选择libc_32.so.6，由于没有相应的libc版本下载，反馈推荐使用的libc版本。
不同的libc版本，即便能运行程序，但libc偏移不相同，会影响你的做题情况
目前提供了-c功能用于加载指定版本的libc，你可以在glibc-all-in-one里下载libc6_2.23-0ubuntu3_amd64.deb后，使用-c功能完成libc加载

**Comment by YOURLEGEND** [comment]
谢谢您的回答，但是从设计的角度我还是保留之前的意见，主要原因如下：
- glibc-all-in-one中包含的libc库版本较少，并不能满足大部分的pwn题或者现实中的二进制程序的需求，因此脚本中的 `-x` 参数可能实际成功率不高
- 当 `-x` 参数不成功时，尝试您说的 `-c` 参数会提示没有对应版本的libc，那我还需要去glibc-all-in-one尝试分别执行 `update_list` 和 `update_old`，在 `list` 和 `old_list` 中找到临近的版本，执行 `download` 或者 `download_old` 脚本进行下载，这是个相当繁琐的过程，并且在此时脚本相对于分别执行脚本中的所有命令只是优化了 `patchelf` 步骤。而且这还是大多数情况

附 `-c` 参数的执行结果
```
$ xclibc -c 2.23 hacknote 
Not support version or your /home/hu/glibc-all-in-one don't have libc
```
这里从实用性的角度出发，建议您可以**选用以下方法其中一种**更简单地解决问题

- 提供直接全部下载 glibc-all-in-one 全部libc的功能，类似项目 [pwn-change-libc](https://github.com/tower111/pwn-change-libc) 的实现，然后加入允许查询所有libc的功能，让用户选取libc进行patch(这一点可以通过将每个libc分别放入一个目录，然后枚举目录名实现，比较轻易)
- 提供根据用户需要的libc实时进行下载的功能，类似项目 [how2heap/glibc_run.sh](https://github.com/shellphish/how2heap/blob/master/glibc_run.sh) 的实现，实际上您的脚本里面已经在 `-x` 参数里提供了根据libc版本下载deb包、解压到相应目录的功能

此外，还有 [libc_changer](https://github.com/t3mp-0xCC/libc_changer/blob/main/libc_changer) 和 [patch_to_libc](https://github.com/am009/patch_to_libc) 等项目可以参考，而且如果使用shell难以实现的功能可以结合python实现，毕竟工具是为了解决问题的。

天下苦 libc 久矣，每次都要因为更换libc移动大量文件和执行大量命令，稍不留神还会因为 `patchelf` 命令错误导致程序跑不起来，希望您的项目可以成为一代pwn选手的经典工具！

**Comment by ef4tless** [comment]
你使用的-c功能的命令不对
```
xclibc -c  hacknote 2.23
```
然后后就会返回对应的全部小版本。
参照你的建议，我完成了一次版本更新，添加了下载libc版本库的功能。但是关于源上没有libc版本，我暂时还没有有效的解决办法，目前的解决办法是在你在网络上下载libc6_2.23-0ubuntu5_i386.deb和libc6-dbg_2.23-0ubuntu5_i386.deb后，用-e功能添加到libs库里。
或许我可以提供一些我曾经下载过但源上已经没有的libc版本库，但我并没有很多的这样的版本

**Comment by ef4tless** [comment]
增加了更多的版本匹配，现在应该能解决你的问题了

**Comment by YOURLEGEND** [comment]
好的，谢谢，用起来很顺手！有bug我会再提issue的
